### ISSUE TITLE
Scroll to index does not work

### ISSUE THREAD

**Issue by jagan999** [marcglasberg/indexed_list_view#1]
I copied the example code as is and tried to run it. When I click on any of the 3 buttons to scroll, it throws this error and does nothing.

I/flutter (32287): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (32287): The following assertion was thrown while dispatching notifications for IndexedScrollController:
I/flutter (32287): A IndexedScrollController was used after being disposed.
I/flutter (32287): Once you have called dispose() on a IndexedScrollController, it can no longer be used.
I/flutter (32287): 
I/flutter (32287): When the exception was thrown, this was the stack:
I/flutter (32287): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
I/flutter (32287): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
I/flutter (32287): #2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:134:12)
I/flutter (32287): #3      ScrollController.dispose (package:flutter/src/widgets/scroll_controller.dart:198:11)
I/flutter (32287): #4      _IndexedListViewState._addPositiveControllerListener.<anonymous closure> (package:indexed_list_view/indexed_list_view.dart:154:30)
I/flutter (32287): #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:161:21)
I/flutter (32287): #6      IndexedScrollController.jumpToIndex (package:indexed_list_view/indexed_list_view.dart:72:7)
I/flutter (32287): #7      _TestPageState.build.<anonymous closure> (file:///C:/Home/AndroidDevelopment/MoneyGuruFlutter/moneyguru/lib/ui/test_page.dart:212:47)
I/flutter (32287): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
I/flutter (32287): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
I/flutter (32287): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (32287): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (32287): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (32287): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (32287): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (32287): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (32287): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter (32287): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (32287): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (32287): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (32287): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (32287): #21     _invoke1 (dart:ui/hooks.dart:142:13)
I/flutter (32287): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)
I/flutter (32287): 
I/flutter (32287): The IndexedScrollController sending notification was:
I/flutter (32287):   IndexedScrollController#f752d(one client, offset 0.0)

**Comment by marcglasberg** [comment]
Ok, I'll have a look in a few moments.

**Comment by jagan999** [comment]
Hello,
Were you able to take a look? Thanks

**Comment by marcglasberg** [comment]
Sorry for the delay. I couldn't reproduce the problem, but then I noticed I was using a newer version from the one in pub.dartlang.org. Could you please download the current version (0.0.4) and tell me if the problem is solved?

**Comment by jagan999** [comment]
The new version throws no error. Thanks for fixing this.

**Comment by jagan999** [comment]
Works wonderfully well. Thanks for this plugin. I'll upvote your work on all forums.
