### ISSUE TITLE
[Feature Request] Quick Navigation (Scrollbar)

### ISSUE THREAD

**Issue by rockingdice** [marcglasberg/indexed_list_view#12]
Thanks for your great work, been using it for a while. Working like a charm. 
I think if someone needs a long list in flutter, they definitely need this.

However, I need a scrollbar for the users to navigate quickly in the list. I think it's a common feature for a list, I found some libs to achieve the same features, but none of them is correctly functioning.
Is that difficult to implement for the indexed list view?

**Comment by marcglasberg** [comment]
But how do you even define the scrollbar position in an infinite list?

**Comment by rockingdice** [comment]
I would like to see it as a finite list but the top and bottom are connected. Each offset of the list can be mapped to an offset in the scrollbar.

So the scrollbar will be reset to the other end if you drag the list exceed the bottom or top. When you drag the scrollbar, the list won't exceed either of its ends, because of the scrollbar in under your finger, it cannot suddenly move to the other end. They could navigate using the scrollbar as a normal one.

**Comment by marcglasberg** [comment]
I believe that's too specific and it's out of the scope of this list. And in any case that seems very difficult to implement with the current indexed_list_view. I have no idea how. Sorry for not being able to help. I'll go on and close this issue.
