### ISSUE TITLE
can I disable the touch scroll and just scroll by programmatically ?

### ISSUE THREAD

**Issue by winsonet** [marcglasberg/indexed_list_view#13]
that's mean user just can click the button for scroll to next item, I don't want the user scroll by touch the listview, I try to set

```physics: NeverScrollableScrollPhysics(),```

but nothing happen :(

thanks!

**Comment by marcglasberg** [comment]
Try again with version **1.0.4**.
It should now work.

**Comment by winsonet** [comment]
thanks!
