### ISSUE TITLE
index_list_view flutter web support required

### ISSUE THREAD

**Issue by devmvk** [marcglasberg/indexed_list_view#16]
Hi , this plugin is great for my device application but i also want this plugin to support flutter web. When i include the plugin dependency in my project i see the following error.

> Because every version of indexed_list_view depends on flutter any from sdk which is forbidden, indexed_list_view is forbidden.
So, because web_demo depends on indexed_list_view ^1.0.7, version solving failed.

Flutter version `v1.9.1+hotfix.2 stable`
Dart version `2.5.0`

**Comment by marcglasberg** [comment]
I haven't had the chance to play with Flutter Web, and I have no idea how to fix this for Flutter web. Do you know what I must change to fix this?
