### ISSUE TITLE
Any way to get header item index that currently display in the view when scrolling?

### ISSUE THREAD

**Issue by sooxt98** [marcglasberg/indexed_list_view#17]

**Comment by marcglasberg** [comment]
Sorry, no there isn't. If you don't need an infinite list you may try this one: 

https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ScrollablePositionedList-class.html

**Comment by sooxt98** [comment]
@marcglasberg Wow, I don't even know this widget exists! How did you know this?

**Comment by marcglasberg** [comment]
@sooxiaotong See: https://github.com/flutter/flutter/issues/12319
