### ISSUE TITLE
How to get current index with callback?

### ISSUE THREAD

**Issue by daveleenew** [marcglasberg/indexed_list_view#18]
Hi,How to get current index with callback?

**Comment by marcglasberg** [comment]
You can't, really. Try this package: https://pub.dev/packages/flutter_widgets

**Comment by anaurelian** [comment]
Unfortunately with ScrollablePositionedList `itemCount` is required.

**Comment by marcglasberg** [comment]
Maybe this can help: https://pub.dev/packages/visibility_detector
