### ISSUE TITLE
How to force the index to always start from zero? 

### ISSUE THREAD

**Issue by Marek00Malik** [marcglasberg/indexed_list_view#19]
I may be thinking about this in an incorrect way. 
So I have a finite rather big list, and I need to have the possibility to jump to each record, so either a callback to get that index or know how to calculate it each time would be a good thing to know. 
Sorry if this is super easy and this question is rather dump, I was checking the net for a correct list implementation for me to be suited with a big list and jump to index features and found your plugin, but could not get to understand how I could utilize it fully in my example.

**Comment by marcglasberg** [comment]
This package is for infinite lists only. If your list is finite you should use another package. Google has one in pub, but I just forgot the name of the package, sorry. Search for it in this package issues, you'll find it (I've recommended it to some other guy).

**Comment by Marek00Malik** [comment]
Thanks, and sory for the invalid issue then :)
