### ISSUE TITLE
Support for Shinkwrap property, like with ListView?

### ISSUE THREAD

**Issue by rjgoodman** [marcglasberg/indexed_list_view#20]
Would it be possible to implement the shrinkwrap property, like ListView has, so that the IndexedListView doesn't expand to take up all of the available space given by the parent element when shrinkwrap=true?

**Comment by marcglasberg** [comment]
I don't think it really makes sense for this widget, since it works only for an infinite number of items. And since the number of items is infinite it would expand as much as it can, anyway, unless the widgets were to have zero length, which doesn't make sense.

Sorry, maybe this widget is not exactly what you need?

**Comment by rjgoodman** [comment]
I was thinking in terms of the left and right borders, not the top and bottom. Right now, the Indexed List View stretches to the full width of the parent.

**Comment by marcglasberg** [comment]
From the shrinkWrap docs: 

_Whether the extent of the scroll view in the scrollDirection should be determined by the contents being viewed. If the scroll view does not shrink wrap, then the scroll view will expand to the maximum allowed size in the scrollDirection. If the scroll view has unbounded constraints in the scrollDirection, then shrinkWrap must be true._

In other words, shrinkWrap doesn't affect the width of the parent when the scrollDirection is vertical. So even the original ListView can't do what you ask for.

**Comment by rjgoodman** [comment]
Ah, ok, I hadn't realized that. Thanks!

**Comment by marcglasberg** [comment]
No problem.
