### ISSUE TITLE
loading more data

### ISSUE THREAD

**Issue by taozhipeng1990** [marcglasberg/indexed_list_view#26]
This is a great plugin.
However, when I use it, I cannot load more data.
I try to load it when judging the index range in itemBuilder,
Or judge index<-10 or index>length+10 in emptyItemBuilder,
But the effect is not ideal.

这是一个很棒的插件。
但是，我在使用时，无法实现加载更多数据。
我尝试在 itemBuilder 中 判断 index范围时 进行加载、
或是在 emptyItemBuilder 中 判断 index<-10 or index>length+10,
但是效果都不理想。

**Comment by marcglasberg** [comment]
Ok, but what exactly is the problem and what's your proposed solution?
