### ISSUE TITLE
Require shrinkWrap property to work with slivers.

### ISSUE THREAD

**Issue by tehsunnliu** [marcglasberg/indexed_list_view#30]
Same as ScrollablePositionedList, indexed_list_view also lacks the mentioned property.
Please add this feature.

**Comment by marcglasberg** [comment]
With `shrinkWrap: true`, a `ListView` only occupies the space it needs, when the sum of its items is smaller than the available space. A `ScrollablePositionedList` is finite, so it makes sense to have this parameter. An IndexedListView, however, is infinite. It works only with an infinite number of items. For this reason, no matter how small are the items, they will never fit a space smaller than the available space. Therefore, `shrinkWrap: true` doesn't make sense here.

**Comment by tehsunnliu** [comment]
Oh. Thank you so much for the information. I was trying to implement IndexedListView with NestedScrollView and SliverAppBar, however, I was not able to get the scrolling to work. Ill try again.
