### ISSUE TITLE
Can i set scroll limit for top and bottom scrolling???

### ISSUE THREAD

**Issue by darshakpranpariya** [marcglasberg/indexed_list_view#31]
Can i set scroll limit for top and bottom scrolling???

**Comment by xarmatura** [comment]
The same question, could you please add someone flag to disable infinity scroll? @marcglasberg

**Comment by marcglasberg** [comment]
Sorry folks, it's not possible. This widget is just for infinite scroll, I am afraid. I should have named it infinite_scroll_list_view or something. But now I can't change that name.
