### ISSUE TITLE
Infinite limitation

### ISSUE THREAD

**Issue by juvanjan** [marcglasberg/indexed_list_view#32]
Is there a way to get rid of infinite scrolling limitation?

I can limit negative side by setting minScrollExtent to 0. However I'm unable (perhaps simply too underexperianced) to calculate maxScrollExtent as I have a list of items with variable heights.

**Comment by marcglasberg** [comment]
No. An indexed_list_view is always infinite. It's out of the scope of this widget to do what you want. 

This question has been asked many times.

**Comment by tonnyavery** [comment]
Out of scope, sure, but nothing prevents you from attaching `onScrollChanged` listener to your controller and limiting your scroll values there.

**Comment by graemep-nz** [comment]
@AAverin is it possible to suggest how to limit the scroll values with onScrollChanged.
