### ISSUE TITLE
FixedExtentScrollPhysics behavior with IndexedListView

### ISSUE THREAD

**Issue by TornadoStorm** [marcglasberg/indexed_list_view#36]
I'm finding this package absolutely essential for my current project, but I feel it misses one feature that would really round it off, physics behavior akin to that of FixedExtentScrollPhysics, where the scrolling focuses on specific items that it smoothly snaps to.

Example:
![Example image of FixedExtentScrollPhysics behavior](https://miro.medium.com/max/1400/1*4XETw8zoeNGGODA77c09Iw.gif)

Is there any possibility that this or something similar could/would be implemented? I believe FixedExtentScrollPhysics itself requires a certain controller to be used, which is incompatible with the IndexedListView, so possibly a new controller would have to be made for this too, or the current IndexedScrollController would need to be modified.

**Comment by marcglasberg** [comment]
No, sorry, this feature is out of scope for this package. I am only doing bug maintenance for this package for the foreseeable future.
