### ISSUE TITLE
how to create a limited items ListView

### ISSUE THREAD

**Issue by sunshineinwater** [marcglasberg/indexed_list_view#6]
such as I want to create a ListView contains 10 card .

"IndexedListView.builder()"  have not such keyword like "itemCount" .
I don't know how to create it ?

**Comment by marcglasberg** [comment]
You can´t. That´s for infinite lists only. Sorry.

**Comment by michinchin** [comment]
Is there a way we can create a finite list? For my project I need to jumpTo(object) in my finite list view

**Comment by marcglasberg** [comment]
If it's finite and not very large, you can do that with a SingleChilScrollView. See this: https://stackoverflow.com/questions/49153087/listview-scrolling-to-widget
