### ISSUE TITLE
List is not scrolling 

### ISSUE THREAD

**Issue by rahuldevanavar91** [marcglasberg/indexed_list_view#7]
Earlier I was using `ListView.builder` that time scrolling works perfectly,

when I replaced with `IndexedListView.builder` list is not scrolling at all.

**Comment by marcglasberg** [comment]
I can't really fix an issue that says "stuff doesn't work" and gives no detail.

**Comment by marcglasberg** [comment]
Version 1.0.0 was released. See if it solved your problem. If not, please post some example code that demonstrates your problem. Thanks.
