### ISSUE TITLE
ETA On Non-Infinite Lists?

### ISSUE THREAD

**Issue by NickM-27** [marcglasberg/indexed_list_view#8]
I really don't want to be *that guy* but I am trying to go to production and the one thing that is stopping me is that I don't have jump to index in normal list view. I found this but unfortunately my use case can not have infinite lists.

**Comment by marcglasberg** [comment]
I have no ETA. I really believe this should be fixed by the Flutter team. I suggest you go to https://github.com/flutter/flutter/issues/12319 and subscribe/vote/complain.
